### ISSUE TITLE
Installing sb cli shows an error during installation script execution for jstyleson

### ISSUE THREAD

**Issue by mocelj** [utkarshayachit/azbatch-starter#38]
<img width="1821" alt="Screenshot 2023-05-05 at 17 35 36" src="https://user-images.githubusercontent.com/12912135/236503560-caac67df-370f-4499-900d-03d05eacd518.png">

Installation stays in pending state w/o progress after the error message.

**Comment by utkarshayachit** [comment]
oops! accidentally commited a work-in-progress change. removed it..fetch code again and try
