### ISSUE TITLE
managed identity on Jumpbox needs write permission to submit a job to Azure Batch

### ISSUE THREAD

**Issue by mocelj** [utkarshayachit/azbatch-starter#42]
Setting up the cli on the Linux Jumpbox was successful. Trying to submit a AzFinSim job with:

sb azfinsim -s $AZ_SUBSCRIPTION_ID -g $AZ_RESOURCE_GROUP -p $AZ_POOL_ID --num-trades 1000  --num-tasks 100 --algorithm "pvonly"  --container-registry "docker.io" --image-name "utkarshayachit/azfinsim:main"

Unfortunately,'Microsoft.Batch/batchAccounts/jobs/write' permission is required for the managed identity to submit a job to Azure Batch. 

sb test were successful. See attached screenshots.

<img width="1636" alt="Screenshot 2023-05-10 at 14 40 59" src="https://github.com/utkarshayachit/azbatch-starter/assets/12912135/d002b1c9-0987-44af-b7eb-17661dc4bd10">

<img width="1636" alt="Screenshot 2023-05-10 at 14 41 32" src="https://github.com/utkarshayachit/azbatch-starter/assets/12912135/b766c84e-a23f-406c-b4a5-e93362668785">

**Comment by utkarshayachit** [comment]
fixed. verified that job submission now works from jumpbox:

![image](https://github.com/utkarshayachit/azbatch-starter/assets/97864/d584b3cb-0dc6-4c28-ab41-83ac4b78f921)
