### ISSUE TITLE
NSG rules missing for Legacy Communication

### ISSUE THREAD

**Issue by mocelj** [utkarshayachit/azbatch-starter#7]
https://github.com/utkarshayachit/azbatch-starter/blob/3eea6f88fd25026592c1e80381cb44d787a50239/config/spoke.json#L16

NSG rules are not complete - suggest to add UDRs to point to the Hub Firewall which will take care of needed communication.

**Comment by utkarshayachit** [comment]
#8 add support for passing UDRs from hub config. We perhaps still need to fix the NSG rules for completeness here.
