### ISSUE TITLE
Likely runtime error upon selecting dataset for visualization — pointers for debugging 

### ISSUE THREAD

**Issue by cardinalgeo** [utkarshayachit/azbatch-starter#71]
Hi Utkarsh! My name is Robert, and I'm a graduate student at McGill University, Canada. I've been working on a trame-based geoscience app and came across your [tutorial](https://utkarshayachit.github.io/azbatch-starter/) on deploying such apps using Microsoft Azure — thank you for putting such a comprehensive resource together. I've seemingly managed to deploy the app using Azure batch, as I'm able to upload dummy datasets (e.g., [can.ex2](https://github.com/Kitware/trame/blob/641cd3e2b176d6dacb55abc708695dfefbca59c9/examples/data/can.ex2) and [disk_out_ref.vtu](https://github.com/Kitware/trame/blob/641cd3e2b176d6dacb55abc708695dfefbca59c9/examples/data/disk_out_ref.vtu) from the trame repo) and view the files in the `vizer-hub` "data portal." An example with just the latter data file: 

<img width="1335" alt="Screenshot 2023-09-12 at 11 43 34 AM" src="https://github.com/utkarshayachit/azbatch-starter/assets/44422832/8b84f627-960c-4aa8-800a-f801aedb2627">

However, when I select a file for visualization using `vizer`, it hangs on `awaiting job to start executing`, and ultimately produces an error such as the following: 

<img width="1381" alt="Screenshot 2023-09-12 at 12 41 51 PM" src="https://github.com/utkarshayachit/azbatch-starter/assets/44422832/e54ceae3-4852-4abd-8a8b-834035958ce2">

I realize that this information alone is insufficient to diagnose the problem. Rather, as a new Azure user, I'm interested in any suggestions for paths to take to effectively evaluate the problem for this particular use case. It's clear that the error is not random (a similar situation has been documented for Azure [here](https://github.com/Azure-Samples/azure-search-openai-demo/issues/420)). I've set up logging for the batch resource and network interface, but didn't notice anything anomalous in the logs (though perhaps your trained eye would identify something if I posted a subset of the logs you think would be relevant?). Any suggestions for how to proceed?

**Comment by utkarshayachit** [comment]
Robert, have you scaled the pool manually already? Browse to the Batch account in Azure Portal and then ensure that the pool (IFNM, is called linux) to have at least one node. Once the pool has been resized successfully (it may take 5/10 mins) try again. I realized that I forgot to include the pool resize step in the tutorial (oops!).

**Comment by cardinalgeo** [comment]
Thanks Utkarsh, I have not scaled the pool so will give that a try. What does IFNM stand for? 

Best, Robert

**Comment by utkarshayachit** [comment]
Opps, I mean "if I am not mistaken"...I clearly just made up a wrong acronym!

**Comment by utkarshayachit** [comment]
let me know if that address the issue. If so, I'll update the vizer-hub code to check for pool size and warn or something before launching. At the very least, I'd like to fix the error to be a bit more comprehensible :).

**Comment by cardinalgeo** [comment]
Will do! Still evaluating the situation. One thing is still perplexing as a new Azure user following the tutorial: upon deploying as instructed using `az deployment sub create`, the deployment automatically fails with the error message `Pool quota for the [batch] account has been reached`. This is seemingly because the pool quota for the batch is set to 0 by default, so the quota is of course automatically reached (why this is the default is unclear to me). However, the newly created batch account remains despite the deployment failure, and I can then submit a request to have its pool quota be increased (e.g., from 0 to 1). Afterwards, running `az deployment sub create` again results in a successful deployment. 

The progression described above is a bit convoluted, but I guess there's no other way to go about this unless the pool quota default is >0. Would a subset of tutorial users have a pool quota >0? If not, it might be worth making a note of this. Another potential solution is to enable the ability to optionally pass info for a batch account (e.g., one whose pool quota has already be increased), as is done for the storage account. Would this be possible?

**Comment by utkarshayachit** [comment]
honestly, the quotas are forever confusing to me. I believe it greatly depends on your subscription. Is the univ managing your subscription? If so, that's where this quota limit is coming from. 

Using a preexising batch account is difficult for this setup since the setup ensures the batch account is setup in a specific way -- assigning approrpiate identities etc. All of that falls apart is an external batch account is provided.

**Comment by cardinalgeo** [comment]
I've tried deployment with accounts set up using both my personal and university emails, and in both cases the pool per batch quota was set to 0 by default — go figure! Anyways, thanks for the clarification regarding external batch accounts. I'll follow up with how your earlier suggestion went once my most recent pool quota increase request is granted. Stay tuned!

**Comment by cardinalgeo** [comment]
Hey @utkarshayachit, scaling the pool did the trick! I added just one node, as you suggested, and am now able to select and visualize datasets. Thanks for the guidance! 

One hiccup I encountered as a new Azure user that I'll record here for others — the default vCPUs-per-node quota for the DSv3 series is 10 (at least for me), and as such, the 32 vCPUs of the Standard_D32s_v3 set in the `config.jsonc` file exceed this, resulting in an error. I've edited the file so that Standard_D8s_v3 is used instead, such that the quota is no longer exceeded, thus resolving the issue. Interaction with the visualization seems a bit laggy relative to the video snippet in your original tutorial; I suspect this is a result of the lower number of CPUs (?)

**Comment by utkarshayachit** [comment]
> I suspect this is a result of the lower number of CPUs

Could be. Also perhaps it's hitting network limits. Depending on the dataset you're loading, the rendering most likely isn't the challenge so could just be network or image compression time. Playing with things like interactive rendering setting in the client may be ways forward.

**Comment by cardinalgeo** [comment]
Gotcha, thanks for the suggestion Utkarsh
